name: Release

on:
  push:
    branches:
      - "*prerelease*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check pre.json existence
        id: check_pre
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3
        with:
          files: ".changeset/pre.json"

      - name: Ensure pre.json exists
        if: steps.check_pre.outputs.files_exists != 'true'
        run: echo "pre.json does not exist, enter prerelease mode with 'pnpm changeset pre enter {prereleaseName}'"; exit 1

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc # v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          version: pnpm run update-version
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
