on:
  workflow_call:
    inputs:
      package_folder:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  check:
    strategy:
      fail-fast: true

    name: Contract sizes
    runs-on: ubuntu-latest
    steps:
      - name: Set initial ${{ inputs.name }} sizes status
        uses: myrotvorets/set-commit-status-action@968047d472cada5abe7920db2b2e539e54e4610e # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Contract ${{ inputs.name }} sizes

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Cache build
        uses: ./.github/actions/cache_foundry_build
        with:
          package_folder: ${{ inputs.package_folder }}

      - name: Check contract sizes
        run: cd ${{ inputs.package_folder }} && pnpm run build:sizes

      - name: Set final ${{ inputs.name }} sizes status
        uses: myrotvorets/set-commit-status-action@968047d472cada5abe7920db2b2e539e54e4610e # v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Contract ${{ inputs.name }} sizes
