name: JS

on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build_js:
    strategy:
      fail-fast: true
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      VITE_CONDUIT_KEY: ${{ secrets.CONDUIT_KEY }}
      VITE_ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}

    name: Build js package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Cache turbo build setup
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Build js package
        run: |
          pnpm turbo run build

      - name: Test js package
        run: |
          pnpm turbo run test:js
