name: Lint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Run prettier
        run: pnpm run lint
